### ISSUE TITLE
Update repository

### ISSUE THREAD

**Issue by StefanPostma** [IgorYbema/update-rooted#1]
Hi Igor,

Any idea for a different repo?

While running the script i get an error setting up the VPN isn't possible.

Could this be because the Toon Subscription isn't valid any more?

Thanks,

Stefan

**Comment by IgorYbema** [comment]
Can you send me your /etc/openvpn/eneco-001-xxxxx.tar.gz file? I can then
check if your vpn should still work or if eneco is blocking you.

2018-06-12 9:56 GMT+02:00 StefanPostma <notifications@github.com>:

**Comment by StefanPostma** [comment]
Will check tomorrow 👍
