### ISSUE TITLE
Unable to determine your current running version (3.4.2)

### ISSUE THREAD

**Issue by gizmocuz** [IgorYbema/update-rooted#10]
The output from the script returns the following:

> Unable to determine your current running version!
> DEBUG information:
> Detected: 3.4.2
> Available: 1.9.10 2.1.0 2.2.24 2.3.17 2.3.29 2.3.36 2.4.7 2.4.12 2.5.11 2.5.14 2                                                                                                  .5.18 2.6.24 2.6.33 2.8.16 2.8.21 2.9.15 2.9.26 3.0.29 3.0.32 3.1.22 3.2.14 3.2.                                                                                                  18 3.2.21 3.3.8 3.4.4 3.5.4 3.6.3 3.7.8 3.7.9 4.3.20 4.4.21 4.7.23 4.8.25 4.9.23                                                                                                   4.9.124 4.10.6 4.11.6 4.12.0 4.13.6 4.13.7 4.15.2 4.15.6 4.16.8 4.18.8 4.19.10                                                                                                   4.20.7 4.22.7
> base-qb2-ene - 3.4.2-986-1
> END DEBUG information
>

if it safe to use the -v version to upgrade to 4.19.10 ?

**Comment by IgorYbema** [comment]
I just added 3.4.2 to the known list. So run again and you will see it work properly. If not -v to 4.10.6 first

**Comment by gizmocuz** [comment]
Thanks, working, currently on  4.10.6, upgrade to 4.22.7 right now (needed to reboot twice)
Great script!! (small typo... verion (version), flavour ene (flavor one?)

```
Could not determine available versions from online sources. Using older well known **verion** list.
You are currently running version 4.10.6 on a qb2 with **flavour ene**
```
