### ISSUE TITLE
Certficaat DomeinServerCA2020.cer is niet meer beschikbaar op de aangegeven locatie! 

### ISSUE THREAD

**Issue by Jopandrik** [IgorYbema/update-rooted#18]
Vorige week kreeg ik tijdens het rooten de volgende foutmelding:

...
EDITING: download certificate store pem file
Adding intermediate Staat der Nederlanden Domein Server CA 2020 - for NLalert API
unable to load certificate
1996055760:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1220:
1996055760:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:tasn_dec.c:386:Type=X509
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
...

Het certificaat DomeinServerCA2020.cer, dat hier geprobeerd wordt op te halen bestaat echter niet meer op de locatie [.](https://cert.pkioverheid.nl/)
Bovendien betreft het een certificaat, dat reeds op dinsdag 6 december 2022 verlopen blijkt te zijn!

Kan iemand de regels 201 t/m 207 uit het update-rooted.sh (laten) verwijderen?

Opmerking: op de Github pagina kan ik geen melding maken m.b.t. dit isue!

**Comment by IgorYbema** [comment]
Just updated the code. Thank you
